### PR TITLE
kraft.yaml: Use stable version for all components

### PR DESCRIPTION
**Pull request by razvand**
This has the benefit of not requiring updates whenever there is a new version release of Unikraft components.

### CODE REVIEW

**Review by eduardvintila — CHANGES_REQUESTED** [review]
Hello, @razvand. The stable branch of `compiler-rt` doesn't have the `ukmmap` dependency selected, so building the application fails. I think we can either use `version: staging` for `compiler-rt`, or update the stable branch of `compiler-rt` to include the `ukmmap` dependency from the `staging` branch

**Comment by razvand** [comment]
@eduardvintila , we will use a `stable` version for all libraries when we do the release. I suggest we approve this PR and get things ready for the release.

**Review by eduardvintila — APPROVED** [review]
Things are looking good! Thanks, @razvand.

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Review by nderjung — APPROVED** [review]
Looks good to me! Thanks!

Approved-by: Alexander Jung <alex@unikraft.io>

**Pull request closed without merging**
